const icons = {
    add: require('./addIcon.svg').default,
    search: require('./searchIcon.svg').default,
    menu: require('./menuIcon.svg').default,
    create: require('./creatorIcon.svg').default,
    language: require('./languageIcon.svg').default,
    help: require('./helpIcon.svg').default,
    keyboard: require('./keyboardIcon.svg').default,
    nightMode: require('./nightModeIcon.svg').default,
    send: require('./sendIcon.svg').default,
    inbox: require('./inboxIcon.svg').default,
    user: require('./userIcon.svg').default,
    favorite: require('./favourite.svg').default,
    tiktok: require('./tiktokIcon.svg').default,
    media: require('./mediaIcon.svg').default,
    setting: require('./settingIcon.svg').default,
    logout: require('./logoutIcon.svg').default,
    home: require('./homeIcon.svg').default,
    homeActive: require('./homeActiveIcon.svg').default,
    friends: require('./friendsIcon.svg').default,
    friendsActive: require('./friendsActiveIcon.svg').default,
    explorer: require('./exploxerIcon.svg').default,
    explorerActive: require('./exploxerActiveIcon.svg').default,
    media: require('./mediaIcon.svg').default,
    mediaActive: require('./mediaActiveIcon.svg').default,
    user: require('./userIcon.svg').default,
    userActive: require('./userActiveIcon.svg').default,
    
}

export default icons